#ARG BASE_IMAGE_RELEASE='9'
#ARG BASE_IMAGE_TAG='9.6'

ARG BASE_IMAGE_RELEASE='10'
ARG BASE_IMAGE_TAG='10.2'

ARG USHIFT_VER='4.22'
ARG ACM_VER='2.15'
########################################
FROM registry.redhat.io/rhel${BASE_IMAGE_RELEASE}/rhel-bootc:${BASE_IMAGE_TAG}

ARG ACM_VER
ARG USHIFT_VER

##ARG BASE_IMAGE_RELEASE='9'
##ARG RHEM_RELEASE='1.1'
#
#ARG BASE_IMAGE_RELEASE='10'
#ARG RHEM_RELEASE='1.3'
#
################################################################################
#Red Hat Edge Manager
################################################################################

#RUN dnf config-manager \
#        --set-enabled edge-manager-${RHEM_RELEASE}-for-rhel-${BASE_IMAGE_RELEASE}-$(uname -m)-rpms && \
#    dnf -y install flightctl-agent flightctl-cli && \
#    dnf -y clean all && \
#    systemctl enable flightctl-agent.service && \
#    systemctl mask bootc-fetch-apply-updates.timer 
#
## Optional: To enable podman-compose application support, uncomment below
# RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-${BASE_IMAGE_RELEASE}.noarch.rpm && \
#     dnf -y install podman-compose && \
#     dnf -y clean all && \
#     rm -rf /var/{cache,log} /var/lib/{dnf,rhsm} && \
#     systemctl enable podman.service

     
################################################################################
# Customization
################################################################################

RUN dnf config-manager \
        --set-enabled rhocp-${USHIFT_VER}-for-rhel-9-$(uname -m)-rpms \
        --set-enabled fast-datapath-for-rhel-9-$(uname -m)-rpms 

RUN dnf install -y xz yq podman-plugins inotify-tools firewalld microshift microshift-cert-manager microshift-olm microshift-observability dialog \
                   cockpit cockpit-machines cockpit-podman cockpit-system cockpit-bridge cockpit-pcp cockpit-storaged cockpit-session-recording cockpit-navigator && \
    systemctl enable microshift && \
    systemctl enable microshift-observability && \
    systemctl enable cockpit.socket && \
    dnf clean all

COPY files/ /

RUN chmod +x /usr/local/bin/* && \
    ln -s /usr/lib/systemd/system/first-boot.service /etc/systemd/system/multi-user.target.wants/first-boot.service && \
    ln -s /usr/lib/systemd/system/hook-files.service /etc/systemd/system/multi-user.target.wants/hook-files.service

RUN firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1 && \
    firewall-offline-cmd --zone=public --add-port=22/tcp && \
    firewall-offline-cmd --zone=public --add-port=80/tcp && \
    firewall-offline-cmd --zone=public --add-port=443/tcp && \
    firewall-offline-cmd --zone=public --add-port=6443/tcp && \
    firewall-offline-cmd --zone=public --add-port=30000-32767/tcp
